### ISSUE TITLE
Player Blocking

### ISSUE THREAD

**Issue by CullenIO** [Poheart/FACEIT-HELPER#24]
Requested by Reddit user snimix
> Would it be possible to add a blocking function for players?
> 
> More precisely ... if I block someone and the next game the person is back in the group that I do not have to accept and a new game is searched automatically

**Comment by Poheart** [comment]
That is totally possible to add, and maybe the list can be modified in chrome extension setting page.
But first, i want to focus on multi game supports on FACEIT and will be work on that when i have time (which i really don't for the moment)

**Comment by Poheart** [comment]
Commit 598d3a8f81f063c0e08ed4d6c642add85eb798c3 should achieve feature mentioned in this issue

**Comment by Poheart** [comment]
Issue closed, feature implemented
